# Generated by Django 6.1.2 on 2026-10-09 10:03
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="devices.device",
                verbose_name="measurements",
            ),
        ),
    ]
