[project]
name = "awesome-python-project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14.1"
dependencies = [
    "django",
    "django-rest-framework",
    "django-simple-docs",
    "djangorestframework-simplejwt[crypto]",
    "gunicorn",
    "psycopg[binary]",
    "redis",
    "rq",
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
test = [
    "covdefaults",
    "fakeredis",
    "pytest",
    "pytest-cov",
    "pytest-django",
    "pytest-randomly",
    "pytest-xdist",
    "time-machine",
]

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]

[tool.autoflake]
recursive = true

[tool.mypy]
files = "."
ignore_missing_imports = true
strict = true
exclude = [
    "tests/",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"

[tool.coverage.run]
plugins = [
    "covdefaults",
]
omit = [
    "manage.py",
    "testing/**",
    "kamleon/asgi.py",
    "kamleon/wsgi.py",
    "kamleon/settings/*.py",
]

[tool.coverage.html]
directory = "artifacts/htmlcov/"
