# Generated by Django 6.1.2 on 2026-10-09 10:03
from django.db import migrations
from django.db import models

import kamleon.devices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=kamleon.devices.models.default_serial_number,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("FAULTY", "Faulty"),
                        ],
                        default="INACTIVE",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
