# Generated by Django 6.1.2 on 2026-10-07 22:22
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="identity.customer",
                verbose_name="devices",
            ),
        ),
    ]
