---
name: Build Docker Image

on:
  push:
    paths:
      - Dockerfile
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: .
          push: false
          tags: latest
